version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    volumes:
      - .:/var/www
    ports:
      - "8085:8000"
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=Demo
      - DB_USERNAME=root
      - DB_PASSWORD=236753
    command: ["./wait-for-mysql.sh", "mysql", "php-fpm"]

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Demo
      MYSQL_USER: root
      MYSQL_PASSWORD: 236753
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8082:80"
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge

